### ISSUE TITLE
Assignment-5

### ISSUE THREAD

**Issue by n-grace-henry** [n-grace-henry/Assignment-5#1]
For this assignment I made some exploratory figures in an R script that is in the analysis folder. These figures helped me to figure out what needed to be cleaned in the dataset. I edited one datapoint that seemed like a typo. I made one expository figure that compares length vs weight for every different location. All figures are saved as pdfs in the figures folder.

**Comment by mdscheuerell** [comment]
Nice job with this assignment, Grace.

One piece of advice I have would be to adjust the "alpha" values on the colors to make them somewhat translucent, which would allow folks to see the darker points hiding under the others.
